#!/usr/bin/env bash

usage() {
    declare -r script_name=$(basename "$0")
    echo """
Usage:
"${script_name}" [option] <name>

Option:
    --overall_restore <INT>
    --incremental_restore <INT>
    --submission <INT>
    --app_download <INT>
    --multimedia <INT>
    --default_server <INT>
"""
}


change_limits() {
    cfg_file=$1
    zone=$2
    bucket_name=$3
    rate_limit=$4
    old_config=`grep -E "^limit_req_zone .*${bucket_name}.*${zone}" ${cfg_file}`
    if [[ ! -z "$old_config" ]]; then
      new_config="limit_req_zone \$${bucket_name} zone=${zone}:10m rate=${rate_limit}r/s;"
      sed -i "s[$old_config[$new_config[g" ${cfg_file}
    fi
}

main() {
    if [[ $# -eq 0 ]]; then
        usage
        exit 1
    fi

    OPTIONS=$( getopt -a -o '' -l help,overall_restore:,incremental_restore:,submission:,app_download:,multimedia:,default_server: -- "$@" )

    if [[ $? -ne 0 ]] ; then
        usage ; exit 1
    fi

    eval set -- "$OPTIONS"

    while true
    do
        case $1 in
        
        --help) usage; exit 0 ;;

        --overall_restore) overall_restore=$2; shift 2;;
        
        --incremental_restore) incremental_restore=$2; shift 2;;
        
        --submission) submission=$2; shift 2;;

        --app_download) app_download=$2; shift 2;;

        --multimedia) multimedia=$2; shift 2;;

        --default_server) default_server=$2; shift 2;;

        --) shift ; break ;;
        esac
    done


    cfg_file='/etc/nginx/sites-available/icds_cas_commcare'
    
    /usr/sbin/service nginx configtest
    if [ $? -eq 0 ]; then
        cp $cfg_file /tmp
    else
        echo "Nginx conf is not correct. Manual intervention is required."
        exit 1

    if [[ "$incremental_restore" ]]; then
            change_limits "$cfg_file" "incremental_restore" "incremental_sync" "$incremental_restore"
    fi

    if [[ "$overall_restore" ]]; then
            change_limits "$cfg_file" "overall_restore" "global_limit" "$overall_restore"
    fi

    if [[ "$submission" ]]; then
            change_limits "$cfg_file" "submission" "global_limit" "$submission"
    fi

    if [[ "$app_download" ]]; then
            change_limits "$cfg_file" "app_download" "global_limit" "$app_download"
    fi

    if [[ "$multimedia" ]]; then
           change_limits "$cfg_file" "multimedia" "global_limit" "$multimedia"
    fi

    if [[ "$default_server" ]]; then
             change_limits "$cfg_file" "server_name" "global_limit" "$default_server"
    fi

    /usr/sbin/service nginx configtest

    if [ $? -eq 0 ]; then
            systemctl reload nginx
    else
        cp /tmp/icds_cas_commcare $cfg_file
	    echo "Nginx conf is not correct. Manual intervention is required."
        exit 1
    fi
}


main "$@"
