---
- name: Install Erlang dependencies (Jammy)
  apt:
    name: erlang
    state: present
  when: ansible_distribution_version == '22.04'

- name: Blacklist Erlang from unattended upgrades
  # prevent unattended rabbitmq restart disrupting celery
  lineinfile:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: '^Unattended-Upgrade::Package-Blacklist \{'
    regexp: '^\s*"erlang";'
    line: '    "erlang";'

- name: Add trusted key
  apt_key:
    url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    state: present

- name: Add rabbitmq official apt repository
  apt_repository:
    repo: 'deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu {{ ansible_distribution_release|lower }} main'
    state: present
    update_cache: yes

- name: Install package
  apt:
    name: "rabbitmq-server={{ rabbitmq_version }}"
    update_cache: yes
    state: present
  ignore_errors: '{{ ansible_check_mode }}'

- name: Enable rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_tracing,rabbitmq_federation
    state: enabled
  notify:
  - restart rabbitmq
