---
# Stage 3 of PostgreSQL upgrade
#
# Usage:
#   commcare-cloud <env> ansible-playbook pg_upgrade_finalize.yml --limit pg0,pg1 \
#     -e old_version=9.6 -e new_version=12
#
- hosts: all
  any_errors_fatal: true
  become: yes
  vars:
    new_version_service: "postgresql@{{ new_version }}-main.service"
    old_version_service: "postgresql@{{ old_version }}-main.service"
    new_pg_port: "{{ postgresql_port }}"
    is_standby: "{{ inventory_hostname in groups.get('pg_standby', []) }}"
    log_file: "/opt/data/postgresql/pg_upgrade_{{old_version}}_{{new_version}}.log"
  vars_files:
    - roles/postgresql_base/defaults/main.yml
  vars_prompt:
    - name: confirm_upgrade
      prompt: |

        ===================================================================================
        This will finalize the upgrade and start all the services including standbys.

        Once this playbook completes it will not be possible to roll back without
        restoring from a backup.
        ===================================================================================
        Respond with [y/N]
      private: no
  tasks:
    - name: assert response
      assert:
        that: confirm_upgrade == 'y'

    - service_facts:

    - assert:
        that: force|default('no') == 'yes' or item not in ansible_facts.services or ansible_facts.services.get(item).state == 'stopped'
        msg: |
          {{ item }} is running. This is an unexpected state.

          However it should still be safe to run this playbook though it may encounter errors.

          To run it anyway use '-e force=yes'.
      loop:
        - "{{ new_version_service }}"
        - "{{ old_version_service }}"

    - name: Start primaries
      service:
        name: "{{ new_version_service }}"
        state: started
      when: not is_standby

    - service_facts:

    - assert:
        that: ansible_facts.services.get(new_version_service).state == 'running'
        msg: |
          {{ new_version_service }} is not running. Check log files for the issue.
      when: not ansible_check_mode and not is_standby

    - name: Create replication slots
      become_user: postgres
      pg_replication_slot:
        name: "{{ item }}"
        port: "{{ new_pg_port }}"
        state: present
      vars:
        ansible_ssh_pipelining: true
      with_items: "{{ postgresql_replication_slots|default([]) }}"
      when: not ansible_check_mode and not is_standby

    - name: Start standbys
      service:
        name: "{{ new_version_service }}"
        state: started
      when: is_standby

    - service_facts:

    - assert:
        that: ansible_facts.services.get(new_version_service).state == 'running'
        msg: |
          {{ new_version_service }} is not running. Check log files for the issue.
      when: not ansible_check_mode and is_standby

    - name: Re-enable monit for v{{ new_version }}
      monit_tmp:
        name: "postgresql_{{ new_version }}"
        state: monitored

    - pause:
        seconds: 0
        prompt: |

          Upgrade complete. You should verify that all services are running correctly.

          - Check the PostgreSQL log files for any error output (check primaries and standbys)
          - Check the upgrade log ({{log_file}}) for any post-upgrade steps

          To change ports or other settings use the "deploy_postgres.yml" playbook.
