# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: commcare-cloud tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-22.04"]

    runs-on: ${{ matrix.os }}

    env:
      CI_TEST: 1
      TEST: main

    steps:
    - uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Create ansible log file
      run: |
        sudo touch /var/log/ansible.log
        sudo chown $USER:$USER /var/log/ansible.log
        sudo chmod 644 /var/log/ansible.log

    - name: Install dependencies
      run: |
        source control/init.sh
        # Install test dependencies second to prevent them from being
        # uninstalled by `uv sync` in init.sh
        uv sync --locked --group test

    - name: Run tests
      run: |
        source .venv/bin/activate
        .tests/tests.sh
