# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Filesystem Scan (General repo vulnerabilities)
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.21.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-fs-results.sarif'
          severity: 'CRITICAL'

      - name: Upload filesystem scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-fs-results.sarif'
          category: "trivy-filesystem"

      # Terraform / IaC Scan (Important for your infra work)
      - name: Run Trivy Terraform (IaC) scan
        uses: aquasecurity/trivy-action@0.21.0
        with:
          scan-type: 'config'
          scan-ref: './environments'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-terraform-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Terraform scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-terraform-results.sarif'
          category: "trivy-terraform"
